
GET http://localhost:3000/user/22 HTTP/1.1

Content-Type: application/json



###
POST http://localhost:3000/user/add HTTP/1.1

content-type: application/json
Content-Type: application/raw

{
    "name":"Dave",
    "age":"20"
}

###

GET http://localhost:3200/ HTTP/1.1
